"use client";
import { Component, useRef, useMemo, useEffect, useState, type ReactNode } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, Lightformer } from "@react-three/drei";
import { type MotionValue } from "framer-motion";
import * as THREE from "three";
import Image from "next/image";
type Props={progress:MotionValue<number>;tint:string;reduced:boolean;angle:number;paused:boolean};
function Sculpture({progress,tint,reduced,angle,paused}:Props){
 const root=useRef<THREE.Group>(null);const parts=useRef<(THREE.Group|null)[]>([]);const lenses=useRef<(THREE.Mesh|null)[]>([]);const elapsed=useRef(0);
 const bridge=useMemo(()=>new THREE.CatmullRomCurve3([new THREE.Vector3(-.24,.19,0),new THREE.Vector3(0,.3,0),new THREE.Vector3(.24,.19,0)]),[]);
 const temple=useMemo(()=>new THREE.CatmullRomCurve3([new THREE.Vector3(0,0,0),new THREE.Vector3(.07,.02,-.4),new THREE.Vector3(.09,-.03,-1.7),new THREE.Vector3(.02,-.25,-2.05)]),[]);
 useFrame((state,delta)=>{if(!root.current)return;if(!paused&&!reduced)elapsed.current+=delta;const p=reduced?0:progress.get();const explode=THREE.MathUtils.smoothstep(p,.3,.75);const damp=1-Math.exp(-delta*5);root.current.rotation.y=THREE.MathUtils.lerp(root.current.rotation.y,-.28+angle*Math.PI/180+p*1.9+(reduced?0:state.pointer.x*.13),damp);root.current.rotation.x=THREE.MathUtils.lerp(root.current.rotation.x,.16-p*.3+(reduced?0:state.pointer.y*.08),damp);root.current.rotation.z=-.12+p*.2;root.current.position.y=Math.sin(elapsed.current*.7)*.045;root.current.position.x=p*.85;parts.current.forEach((part,i)=>{if(part)part.position.x=(i===0?-1:1)*(1.02+explode*.35)});lenses.current.forEach(lens=>{if(lens)lens.position.z=explode*.85});});
 return <group ref={root}>{[-1,1].map((side,i)=><group key={side} ref={el=>{parts.current[i]=el}} position={[side*1.02,0,0]}>
 <mesh scale={[1,.94,1]}><torusGeometry args={[.81,.033,16,120]}/><meshStandardMaterial color={tint} metalness={1} roughness={.15}/></mesh>
 <mesh ref={el=>{lenses.current[i]=el}} scale={[1,.94,1]}><circleGeometry args={[.78,80]}/><meshPhysicalMaterial color="#c9c8ab" roughness={.07} metalness={.18} transparent opacity={.18} side={THREE.DoubleSide} depthWrite={false}/></mesh>
 <group position={[side*.82,.07,0]} scale={[side,1,1]}><mesh><tubeGeometry args={[temple,48,.027,10,false]}/><meshStandardMaterial color={tint} metalness={1} roughness={.2}/></mesh><mesh position={[.08,-.08,-1.76]} rotation={[Math.PI/2,0,0]}><capsuleGeometry args={[.047,.33,5,16]}/><meshStandardMaterial color="#342a21" roughness={.25}/></mesh></group>
 <mesh position={[-side*.68,-.2,-.085]} scale={[.067,.12,.04]} rotation={[0,0,side*.3]}><sphereGeometry args={[1,20,20]}/><meshPhysicalMaterial color="#e7dfc5" transparent opacity={.8} roughness={.3}/></mesh>
 <mesh position={[side*.82,.07,0]}><boxGeometry args={[.13,.07,.07]}/><meshStandardMaterial color={tint} metalness={1} roughness={.13}/></mesh>
 </group>)}<mesh><tubeGeometry args={[bridge,24,.025,10,false]}/><meshStandardMaterial color={tint} metalness={1} roughness={.15}/></mesh><mesh position={[0,.29,.028]}><sphereGeometry args={[.043,20,20]}/><meshStandardMaterial color="#eee4ce" roughness={.18}/></mesh></group>;
}
class Boundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?this.props.fallback:this.props.children}}
export default function GoldScene(props:Props){const ref=useRef<HTMLDivElement>(null);const [visible,setVisible]=useState(true);useEffect(()=>{const o=new IntersectionObserver(([e])=>setVisible(e.isIntersecting));if(ref.current)o.observe(ref.current);return()=>o.disconnect()},[]);const fallback=<div className="atelier-scene-fallback"><Image src="/models/orphee-03.png" fill alt="Orphée 03 – Produktvisualisierung" sizes="90vw" style={{objectFit:"contain"}}/></div>;return <div ref={ref} className="atelier-canvas" role="img" aria-label="Interaktive 3D-Ansicht der Orphée-Fassung"><Boundary fallback={fallback}><Canvas fallback={fallback} camera={{position:[0,0,7.2],fov:31}} dpr={[1,1.5]} frameloop={visible?"always":"never"} gl={{antialias:true,alpha:true}}><ambientLight intensity={.7}/><directionalLight position={[3,4,5]} intensity={3}/><Sculpture {...props}/><Environment resolution={128}><Lightformer position={[0,5,1]} scale={[10,2,1]} intensity={5}/><Lightformer position={[-4,1,3]} scale={[3,8,1]} intensity={4}/><Lightformer position={[4,-2,2]} scale={[3,5,1]} intensity={3} color="#edd5a4"/></Environment></Canvas></Boundary></div>}
